# Generated by Django 5.2.4 on 2025-08-01 09:48

import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr')], max_length=10, null=True)),
                ('first_name', models.CharField(default='First', max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(default='Last', max_length=100)),
                ('nep_name', models.CharField(blank=True, default='नेपाल', max_length=255, null=True, verbose_name='NepName (In Nepali)')),
                ('father_name', models.CharField(default='Father', max_length=100)),
                ('nep_father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('grandfather_name', models.CharField(blank=True, max_length=100, null=True)),
                ('grandfather_in_law_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_in_law_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Father/Mother Name')),
                ('daughter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('daughter_in_law_name', models.CharField(blank=True, max_length=100, null=True)),
                ('son_name', models.CharField(blank=True, max_length=100, null=True)),
                ('grand_father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, choices=[('Service', 'Service'), ('Business', 'Business')], default='Service', max_length=50, null=True)),
                ('qualification', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('SLC', 'SLC')], default='Bachelor', max_length=50)),
                ('proposer_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(choices=[('Nepalese', 'Nepalese'), ('Indian', 'Indian'), ('Others', 'Others')], default='Nepalese', max_length=20)),
                ('is_aml_crime', models.BooleanField(default=False)),
                ('is_family_politically_involved', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('date_of_birth_ad', models.DateField(blank=True, null=True, verbose_name='Date of Birth (A.D.)')),
                ('dob_bs', nepali_datetime_field.models.NepaliDateField(blank=True, null=True, verbose_name='Date of Birth (B.S.)')),
                ('age_proof_doc', models.CharField(choices=[('Citizenship', 'Citizenship'), ('Passport', 'Passport')], default='Citizenship', max_length=20)),
                ('document_number', models.CharField(default='DOC123456', max_length=100)),
                ('document_issued_date', models.DateField(blank=True, null=True, verbose_name='Issued Date')),
                ('issued_place', models.CharField(blank=True, choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur')], default='Kathmandu', max_length=50, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('temporary_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Temporary Address')),
                ('temporary_district', models.CharField(blank=True, choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur')], max_length=50, null=True)),
                ('house_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ward_no', models.CharField(blank=True, max_length=10, null=True)),
                ('local_unit', models.CharField(blank=True, choices=[('Kathmandu Metropolitan City', 'Kathmandu Metropolitan City'), ('Pokhara Metropolitan City', 'Pokhara Metropolitan City'), ('Lalitpur Metropolitan City', 'Lalitpur Metropolitan City'), ('Biratnagar Metropolitan City', 'Biratnagar Metropolitan City'), ('Bharatpur Metropolitan City', 'Bharatpur Metropolitan City'), ('Birgunj Metropolitan City', 'Birgunj Metropolitan City')], max_length=100, null=True)),
                ('structure', models.CharField(blank=True, choices=[('Metropolitan City', 'Metropolitan City'), ('Sub-Metropolitan City', 'Sub-Metropolitan City'), ('Municipality', 'Municipality'), ('Rural Municipality', 'Rural Municipality'), ('Ward', 'Ward')], max_length=50, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('income_mode', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=20)),
                ('income_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN No.')),
                ('bank_ac_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_ac_no', models.CharField(blank=True, max_length=50, null=True)),
                ('office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('firm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_family_aml_crime', models.BooleanField(default=False)),
                ('is_politically_involved', models.BooleanField(default=False)),
            ],
        ),
    ]
