# Generated by Django 5.2.4 on 2025-08-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='dob_bs',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth (B.S.)'),
        ),
    ]
