# Generated by Django 5.2.4 on 2025-08-03 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_alter_kycmodel_dob_bs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycmodel',
            name='grand_father_name',
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='age_proof_doc',
            field=models.CharField(choices=[('Citizenship', 'Citizenship'), ('Passport', 'Passport'), ('Birth Certificate', 'Birth Certificate'), ('Other', 'Other')], default='Citizenship', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='date_of_birth_ad',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='dob_bs',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='document_issued_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='email',
            field=models.EmailField(blank=True, default='test@example.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='firm_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='first_name',
            field=models.CharField(default='First', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='house_no',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='income_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='income_mode',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Business', 'Business'), ('Investment', 'Investment'), ('Other', 'Other')], default='Salary', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='issued_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='last_name',
            field=models.CharField(default='Last', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='local_unit',
            field=models.CharField(choices=[('Municipality', 'Municipality'), ('Sub-Metropolitan', 'Sub-Metropolitan'), ('Metropolitan', 'Metropolitan'), ('Rural Municipality', 'Rural Municipality')], default='Municipality', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='mobile',
            field=models.CharField(default='9800000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='mother_father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='nationality',
            field=models.CharField(default='Nepali', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='nep_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='pan_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='proposer_full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='salutation',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr')], default='Mr', max_length=10),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='structure',
            field=models.CharField(choices=[('Concrete', 'Concrete'), ('Wood', 'Wood'), ('Mixed', 'Mixed')], default='Concrete', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='temporary_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='temporary_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='ward_no',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
