# Generated by Django 5.2.4 on 2025-08-03 06:54

import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_remove_kycmodel_grand_father_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycmodel',
            old_name='grandfather_name',
            new_name='father_mother_name',
        ),
        migrations.RenameField(
            model_name='kycmodel',
            old_name='mother_father_name',
            new_name='grand_father_name',
        ),
        migrations.AddField(
            model_name='kycmodel',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kycmodel',
            name='address_nepali',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kycmodel',
            name='birth_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='dob_bs',
            field=nepali_datetime_field.models.NepaliDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='local_unit',
            field=models.CharField(choices=[('Municipality', 'Municipality'), ('Sub-Metropolitan', 'Sub-Metropolitan'), ('Metropolitan', 'Metropolitan'), ('Rural Municipality', 'Rural Municipality')], default='Kathmandu Metropolitan City', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='structure',
            field=models.CharField(choices=[('Metropolitan City', 'Metropolitan City'), ('Sub-Metropolitan City', 'Sub-Metropolitan City'), ('Municipality', 'Municipality'), ('Rural Municipality', 'Rural Municipality'), ('Ward', 'Ward')], default='Concrete', max_length=50),
        ),
    ]
