# Generated by Django 5.2.4 on 2025-08-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_rename_grandfather_name_kycmodel_father_mother_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='local_unit',
            field=models.CharField(choices=[('Municipality', 'Municipality'), ('Sub-Metropolitan', 'Sub-Metropolitan'), ('Metropolitan', 'Metropolitan'), ('Rural Municipality', 'Rural Municipality')], default='Municipality', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='structure',
            field=models.CharField(choices=[('Metropolitan City', 'Metropolitan City'), ('Sub-Metropolitan City', 'Sub-Metropolitan City'), ('Municipality', 'Municipality'), ('Rural Municipality', 'Rural Municipality'), ('Ward', 'Ward')], default='Metropolitan City', max_length=50),
        ),
    ]
