# Generated by Django 5.2.4 on 2025-08-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_alter_kycmodel_local_unit_alter_kycmodel_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='nationality',
            field=models.CharField(default='Nepalese', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='qualification',
            field=models.CharField(blank=True, choices=[('SLC', 'SLC'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
