# Generated by Django 5.2.4 on 2025-08-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_alter_kycmodel_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='issued_place',
            field=models.CharField(blank=True, choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='profession',
            field=models.CharField(choices=[('Service', 'Service'), ('Business', 'Business'), ('Other', 'Other')], default='Service', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='ward_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
