# Generated by Django 5.2.4 on 2025-08-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0007_alter_kycmodel_issued_place_alter_kycmodel_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='local_unit',
            field=models.CharField(choices=[('Kathmandu Metropolitan City', 'Kathmandu Metropolitan City'), ('Pokhara Metropolitan City', 'Pokhara Metropolitan City'), ('Lalitpur Metropolitan City', 'Lalitpur Metropolitan City'), ('Biratnagar Metropolitan City', 'Biratnagar Metropolitan City'), ('Bharatpur Metropolitan City', 'Bharatpur Metropolitan City'), ('Birgunj Metropolitan City', 'Birgunj Metropolitan City')], default='Municipality', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='middle_name',
            field=models.CharField(default='Middle', max_length=50),
        ),
    ]
