# Generated by Django 5.2.4 on 2025-08-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0008_alter_kycmodel_local_unit_alter_kycmodel_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='nationality',
            field=models.CharField(choices=[('Nepalese', 'Nepalese'), ('Indian', 'Indian'), ('Other', 'Other')], default='Nepalese', max_length=50),
        ),
    ]
