# Generated by Django 5.2.4 on 2025-08-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0009_alter_kycmodel_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='kycmodel',
            name='kyc_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
