# Generated by Django 5.2.4 on 2025-08-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0010_remove_kycmodel_id_kycmodel_kyc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='middle_name',
            field=models.CharField(max_length=50),
        ),
    ]
