# Generated by Django 5.2.4 on 2025-08-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0010_alter_kycmodel_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycmodel',
            name='national_id_no',
            field=models.CharField(default=2, max_length=20, verbose_name='Document Number'),
            preserve_default=False,
        ),
    ]
