# Generated by Django 5.2.4 on 2025-08-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0011_alter_kycmodel_first_name_alter_kycmodel_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='middle_name',
            field=models.CharField(max_length=100),
        ),
    ]
