# Generated by Django 5.2.4 on 2025-08-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0012_alter_kycmodel_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
