# Generated by Django 5.2.4 on 2025-08-06 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0013_alter_kycmodel_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycmodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='kycmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
