# Generated by Django 5.2.4 on 2025-08-12 08:44

import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0014_kycmodel_created_date_kycmodel_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycmodel',
            name='document_issued_date_bs',
            field=nepali_datetime_field.models.NepaliDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='document_number',
            field=models.CharField(max_length=100, verbose_name='Document Number'),
        ),
    ]
