# Generated by Django 5.2.4 on 2025-08-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0015_kycmodel_document_issued_date_bs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycmodel',
            name='risk_category',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10, verbose_name='Risk Category'),
        ),
    ]
