# Generated by Django 5.2.4 on 2025-08-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0016_alter_kycmodel_national_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='national_id_no',
            field=models.CharField(max_length=12, null=True, verbose_name='National ID No'),
        ),
    ]
